load("//:defs.bzl", "forestx_rust_crate")

SCHEMA_FIXTURES = glob(
    ["schema/generated/*.json"],
    allow_empty = False,
)

forestx_rust_crate(
    name = "hooks",
    compile_data = SCHEMA_FIXTURES,
    crate_name = "forestx_hooks",
    integration_compile_data_extra = SCHEMA_FIXTURES,
    test_data_extra = SCHEMA_FIXTURES,
)
