# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

version: 2
updates:
  - package-ecosystem: bun
    directory: .github/actions/forestx
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: cargo
    directories:
      - forestx-rs
      - forestx-rs/*
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: docker
    directory: forestx-cli
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: rust-toolchain
    directory: forestx-rs
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
