[package]
edition.workspace = true
license.workspace = true
name = "forestx-model-provider-info"
version.workspace = true

[lib]
doctest = false
name = "forestx_model_provider_info"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
forestx-api = { workspace = true }
forestx-protocol = { workspace = true }
http = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
forestx-utils-absolute-path = { workspace = true }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
