[package]
edition.workspace = true
license.workspace = true
name = "forestx-cloud-tasks-client"
version.workspace = true

[lib]
name = "forestx_cloud_tasks_client"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
forestx-api = { workspace = true }
forestx-backend-client = { workspace = true }
forestx-git-utils = { workspace = true }
forestx-http-client = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
