[package]
name = "forestx-arg0"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "forestx_arg0"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
forestx-apply-patch = { workspace = true }
forestx-exec-server = { workspace = true }
forestx-install-context = { workspace = true }
forestx-linux-sandbox = { workspace = true }
forestx-sandboxing = { workspace = true }
forestx-shell-escalation = { workspace = true }
forestx-utils-absolute-path = { workspace = true }
forestx-utils-home-dir = { workspace = true }
dotenvy = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
forestx-windows-sandbox = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
